version: "3.8"

services:
  server:
    container_name: blend_server
    image: nginx:1.19.2
    volumes: 
      - ./server/nginx.conf:/etc/nginx/nginx.conf
      - ./server/error.log:/etc/nginx/error_log.log
      - ./server/cache/:/etc/nginx/cache
    ports: 
      - "80:80"
    networks: 
      - main
    restart: on-failure
    depends_on: 
      - client
  client:
    container_name: blend_client
    image: alvarofblanco/blend_client:stage
    ports: 
      - "3333:3333"
    networks: 
      - main
    depends_on: 
      - cms
    environment: 
      - CATEGORIA_MUSICA=${CATEGORIA_MUSICA}
      - CATEGORIA_CINE=${CATEGORIA_CINE}
      - CATEGORIA_CULTURA=${CATEGORIA_CULTURA}
      - CATEGORIA_GASTRONOMIA=${CATEGORIA_GASTRONOMIA}
  cms:
    container_name: blend_cms
    image: alvarofblanco/blend_cms:stage
    ports:
      - "1337:1337"
    networks: 
      - main
    depends_on: 
      - db
    environment: 
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  db:
    container_name: blend_db
    image: mongo:4.4.1
    volumes: 
      - db_data:/data/db
    restart: always
    networks: 
      - main
    environment: 
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
networks: 
  main:
    driver: bridge
volumes: 
  db_data: