FROM node:14.15.4-alpine

# App work directory
WORKDIR /usr/src/client

# Install app dependancies
COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

ENV NODE_ENV=development

EXPOSE 3333

CMD ["npm", "run", "dev"]